if [[ $WSFILES_OS == 'osx' ]]; then
    alias ls='ls -GF'
else
    alias ls='ls --color=auto'
    alias open='xdg-open'
fi

alias l='ls -lh'
alias ll='ls -lah'

alias wscd="cd $WSFILES"
alias wsrl='source ~/.zshrc'

alias pyenv='source ./env/bin/activate'

alias d='docker'
alias dco='docker-compose'
alias dcol='docker-compose logs -f --tail=100'

alias k='kubectl'
alias ka='kubectl apply'
alias kc='kubectl create'
alias ke='kubectl edit'
alias kd='kubectl delete'
alias kg='kubectl get'
alias kgd='kubectl get deploy'
alias kgs='kubectl get services'
alias kgp='kubectl get pods'
alias kgn='kubectl get nodes'
alias ki='kubectl cluster-info'
alias kcf='kubectl config'
alias kcfg='kubectl config get-contexts'
alias kcfu='kubectl config use-context'
alias kcfe="$EDITOR ~/.kube/config"
alias kl='kubectl logs'
alias klf='kubectl logs -f --tail 50'
alias kdes='kubectl describe'
alias kpf='kubectl port-forward'

alias g='git'
alias gcl='git clone'
alias gco='git checkout'
alias gcot='git checkout -t'
alias gcob='git checkout -b'
alias gf='git fetch --all --prune'
alias gfa='git_fetch_all && git_scan_directory'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gclean='git clean -df'
alias gclear='git reset --hard HEAD && git clean -xdf'
alias grh='git reset --hard HEAD'
alias glog='git log --all --graph'
alias gd='git diff'
alias gs='git status'
alias gscan='git_scan_directory'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gst='git stash'
alias gsta='git stash apply'
alias gstp='git stash pop'
alias gstl='git stash list'
alias gm='git merge'
alias gpl='git pull'
alias gp='git push'
alias gpa='git push --all'
alias gpt='git push --tags'
alias gpat='git push --all && git push --tags'
